export const SET_MODAL_STATE = 'SET_MODAL_STATE';
export const SET_MODAL_COMPONENT = 'SET_MODAL_COMPONENT';
export const SET_MODAL_COMPONENT_FOOTER = 'SET_MODAL_COMPONENT_FOOTER';

export const SET_ASIDE_STATE = 'SET_ASIDE_STATE';
export const SET_ASIDE_COMPONENT = 'SET_ASIDE_COMPONENT';
